### ISSUE TITLE
Crystal::System::Process#spawn forks, should call posix_spawn() or posix_spawnp() instead

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#11337]
https://github.com/crystal-lang/crystal/blob/9f90efe3315eba17685bb628b8b3e4713f00db5d/src/crystal/system/unix/process.cr#L122
On Unix lookalikes, the `posix_spawn()` and `posix_spawnp()` functions should be available, which would allow this to be implemented without `fork()`. Obviously `fork()` is going to break multithread, and even though this implementation hints that it will `exec()`, there still seems to be unacceptable overhead for large-memory processes.

**Comment by BrucePerens** [comment]
I wrote a benchmark to illustrate the issue. The time difference is convincing. When there are not 3GB of image buffers present, there is still a time difference, just a smaller one.

```
$ time ./spawn 0
Running version 0

real	0m2.231s
user	0m0.765s
sys	0m1.514s
$ time ./spawn 1
Running version 1

real	0m0.394s
user	0m0.060s
sys	0m0.309s


```crystal
lib LibC
  fun clone(func : Void* -> LibC::Int, stack : Void*, flags : LibC::Int) : LibC::Int
  fun execv(LibC::Char*, LibC::Char**) : LibC::Int 
  fun dup2(LibC::Int, LibC::Int) : LibC::Int
end

def do_exec(data : Void*) : LibC::Int
  LibC.dup2(STDOUT.fd, 1)
  command = "/bin/sh\0".to_unsafe
  args = Array(LibC::Char*).new
  args << command
  args << "-c\0".to_unsafe
  args << %Q[echo -n ""\0].to_unsafe
  args << Pointer(LibC::Char).new(0)
  error = LibC.execv(command, args.to_unsafe)
  return error
end

CLONE_VFORK = 0x00004000
CLONE_VM = 0x00000100

stack_array = Array(LibC::Long).new(1000)
# I am told that everything Linux runs upon except for PowerPC grows the stack downwards.
stack = stack_array.to_unsafe + stack_array.size

big_array1 = Array(Char).new(1024 * 1024 * 1024)
# Fault all of those pages in.
big_array2 = big_array1.clone
big_array3 = big_array2.clone

if ARGV.size > 0
  version = ARGV[0].to_i
else
  version = 0
end
STDERR.puts "Running version #{version}"
case version
when 0
  1000.times do
    system(%Q[echo -n ""])
  end
when 1
  1000.times do
    LibC.clone(->(opaque : Void *){ do_exec(opaque) }, stack, CLONE_VFORK|CLONE_VM)
  end
end
```

**Comment by straight-shoota** [comment]
It would be nice to switch to a more efficient mechanism for spawning processes.
* [`vfork`](https://linux.die.net/man/3/vfork) is a portable alternative to `fork`, but it is unsafe for multithreaded processes because only the calling thread is suspended, and the child process shares the same address space with the parent process (and its unsuspended other threads).
* [`posix_spawn`](https://man.archlinux.org/man/posix_spawn.3) is a portable alternative for the entire `fork`+`exec` sequence. It's efficient and safe for multithreaded processes. It allows configuring some actions that happen in between, such as resetting sigmask.

So `posix_spawn` seems like it could be a good improvement over the current implementation.

I'm not quite sure if there's a reason why we didn't use this in Crystal in the first place. Maybe we need to do something that it cannot do?
The `after_fork_before_exec` handlers seem to only reset sigmask and close some file descriptors. This should be possible to implement with `posix_spawn`. There is only one odd thing: [`EventLoop::Polling#after_fork_before_exec`](https://github.com/crystal-lang/crystal/blob/59154962a04eb1991074b3951c8ecacdb00ccb18/src/crystal/event_loop/polling.cr#L110-L114) resets the spin lock. But I'm not quite sure why that is necessary... the child process should never use the event loop before it execs.

A limitation of `posix_spawn` is that it does not support Linux's `pidfd`. It would be nice to switch to using `pidfd`, though. It's safer than waiting on `pid` which can fail in some edge cases.

Glibc has `pidfd_spawn` for exactly this purpose. It was relatively recently introduced in kernel 5.4/glibc 2.39. That's quite a jump from our current minimum requirement kernel 4.14/glibc 2.26. And it's a bit shady as I cannot find any manpages for it. It's also not available on musl, so we're gonna need a fallback anyway.

We could port `pidfd_spawn` to Crystal, making use of Linux's [`clone`/`clone3`](https://man.archlinux.org/man/clone.2.en).

I'm not familiar with details of other Unix systems, but since `pidfd` is specific to Linux, `posix_spawn` should be fine anywhere else.

I think the first step should be adopting `posix_spawnp`. And after that we may look into adding `pidfd` support on Linux.

**Comment by ysbaddaden** [comment]
> I'm not quite sure if there's a reason why we didn't use this in Crystal in the first place.

I guess a mix of fork/exec has been the "unix way" for too long and it looks simpler (it's not).

> `EventLoop::Polling#after_fork_before_exec`

I guess it's related to #14974 and the callback was kept as a safeguard (it doesn't hurt). We definitely don't need it with `posix_spawn` where we won't run any crystal code in the forked process.

> glibc 2.39.

Yeah, that's a jump. Ubuntu 22.04 only has glibc 2.35 for example. Maybe if we supported weak symbols 🤔

Or we port `posix_spawn` / `pidfd_spawn` and detect pidfd support at runtime. Here are the [glibc](https://github.com/bminor/glibc/blob/master/sysdeps/unix/sysv/linux/spawni.c#L310-L483) and [musl-libc](https://git.musl-libc.org/cgit/musl/tree/src/process/posix_spawn.c) implementations.

**Comment by straight-shoota** [comment]
If we want to use `pidfd`, we need to implement our own for `musl` anyway.

**Comment by yxhuvud** [comment]
> There is only one odd thing: [EventLoop::Polling#after_fork_before_exec](https://github.com/crystal-lang/crystal/blob/59154962a04eb1991074b3951c8ecacdb00ccb18/src/crystal/event_loop/polling.cr#L110-L114) resets the spin lock. But I'm not quite sure why that is necessary... the child process should never use the event loop before it execs.

Isn't it necessary in a world where `fork` the actual crystal process is supported from within crystal? It may lose its relevance if/when fork is removed. I hope it is - reasonable usages of fork should be substitutable with exe-ing separate processes.

**Comment by straight-shoota** [comment]
@yxhuvud Yes, if it's just fork without exec, this is required. But note the method name: `after_fork_before_exec`. This method only executes between fork and exec.
For fork-only there's `EventLoop#after_fork`, which does the same thing, though.

**Comment by ysbaddaden** [comment]
Also `Process.fork` isn't supported with `preview_mt` (it won't compile). ~~I think it's high time we deprecate it.~~ It's already deprecated 👍

**Comment by straight-shoota** [comment]
So I guess that means `Process.fork` will be effectively disbanded once we activate execution contexts. It would still technically be possible to use it by opting out of execution contexts. But that should only be a temporary option. So we might be heading for the actual end of `Process.fork`.

**Comment by straight-shoota** [comment]
In order to move to [`posix_spawn`](https://man.archlinux.org/man/posix_spawn.3) or similar, we need to reduce and abstract the housekeeping operations that happen between `fork` and `exec`.

That concerns the following code locations:

https://github.com/crystal-lang/crystal/blob/ca3d4a36dce74b9c0de3ba701eef2ec21d7a197f/src/crystal/system/unix/process.cr#L195-L201

https://github.com/crystal-lang/crystal/blob/ca3d4a36dce74b9c0de3ba701eef2ec21d7a197f/src/crystal/system/unix/process.cr#L317-L336


The individual steps:

* [x] `Crystal::EventLoop#after_fork_before_exec` implementations close a couple of file descriptors and reset a spin lock. As mentioned in https://github.com/crystal-lang/crystal/issues/11337#issuecomment-3382269186, we can probably drop that. (https://github.com/crystal-lang/crystal/pull/16332)
* [ ] Resetting the signal mask seems trivial.
* [ ] `Crystal::System::Signal.after_fork_before_exec` resets all trapped or ignored signals to the default handler and closes the pipes used for communicating signals from the signal handler to the signal loop (no in `preview-mt` though 🤷). This appears a bit copious and convoluted. It was added in #8465 but with a comment that fork can only be used with exec in `preview-mt`, but this specific method is already explicitly for this use case, even without `preview-mt`. 😕 
* [ ] Reopening the standard streams is also quite straightforward. We need to do that because we dup the original file descriptors and need to reset that in the forked process. This can be prepared before the actual fork happens.
* [x] Resetting the environment directly in the process is error-prone and needs to be changed anyway (see #6464). It's also unsafe because `ENV.delete` returns the previous value and thus might allocate. We must strictly avoid that between fork and exec.
  The proper solution is to construct an environment pointer and pass that to `execve`. We can prepare that before the actual fork. `execvpe` would be ideal for this, but it's not portable (it's missing on darwin for example). So we must implement the executable lookup ourselves on top of `execve`. At least for platforms where `execvpe` is missing (https://github.com/crystal-lang/crystal/pull/16322). We cannot use `Process.find_executable` for this though, because it allocates. We can simply port an existing implementation to Crystal (e.g. that from [musl](https://git.musl-libc.org/cgit/musl/tree/src/process/execvp.c) or [cosmo](https://github.com/jart/cosmopolitan/blob/master/libc/proc/execvpe.c) - they're actually quite a bit different).
* [ ] Changing the working directory seems trivial.
* [x] Transforming the arguments into a pointer array can be moved ahead of the fork. (https://github.com/crystal-lang/crystal/pull/16286)

We can only do what's available with `posix_spawnattr` and `posix_spawn_file_actions`:
* Set signal mask
* Reset signal disposition
* Configure scheduler parameters, uid, gid, and cgroup (we probably don't need any of that)
* open, close, dup file descriptors

**Comment by straight-shoota** [comment]
I have an experimental patch for using `posix_spawnp` which shows a working prototype on a couple of targets already.

There are however some shortcomings in mapping the current workflow to the capabilities of `posix_spawn` which we hadn't realized so far.

### `chdir`

The file action for changing the working directory was originally not standardized. `posix_spawn_file_actions_addchdir` has only been added recently in POSIX.1-2024. As a result, the situation is a bit complicated. 
Most implementations have had a non-portable extension for a while (glibc, musl, FreeBSD, darwin, ...: `posix_spawn_file_actions_addchdir_np`). It actually seems to be available pretty much across the board and is portable between them. So maybe that's a misnomer 😆 
We can probably use the non-portable extension on all (?) supported systems. It might not work on older versions, though. For example, bionic requires API version 34. So we might need an alternative to `posix_spawn` on some platforms for compatibility.
The new standard does not seem to be broadly applicable yet.

### Reopening stdios

We're duplicating standard streams it at the start of the Crystal process in order to make them non-blockingand have to revert this trickery before `exec`.
This mechanism has a huge flaw (see #16353) and it's incompatible with `posix_spawn`.

`posix_spawn_file_actions` supports duping, but neither `O_CLOEXEC` nor `O_NONBLOCK`. Even if the latter was safe to do, we couldn't implement it with `posix_spawn`.

**Comment by BrucePerens** [comment]
Perhaps we should test for the presence of `posix_spawn_file_actions_addclose()` and only use `posix_spawn()` in the case that it is implemented. It's from the POSIX Advanced Realtime and while some of that standard portion won't be implemented on all platforms, this function seems to be relatively widely implemented.

**Comment by straight-shoota** [comment]
The problem isn't availability of `posix_spawn` in general. I think it's pretty ubiquitous, including most of the features we need. The potentially missing thing is `posix_spawn_file_actions_addchdir` (or a non-portable alternative like `posix_spawn_file_actions_addchdir_np`).

**Comment by ysbaddaden** [comment]
Do we really have to revert the trickery?

We `dup` the original `fd` and never close it, so we have both the original pristine `fd` and a new internal `fd` with `O_NONBLOCK` that the STD* objects will use. We can keep reading/writing to both, albeit the original should do blocking IO. For example we directly write to stderr (original fd) on fatal errors, panics, etc.

Can't we just pass the original `fd` to `posix_spawn` or `fork` + `exec`, and let the dup be closed thanks to `O_CLOEXEC`? Closing the dup won't close the original.
