### ISSUE TITLE
Metaissue: Improve the interpreter

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11555]
What's missing for the interpreter:

* [ ] #11159
* [ ] Type promotion for variadic arguments
* [ ] `Crystal::Loader` integration
* [ ] Syscalls
* [ ] Pending lib bindings (libxml, libyaml)
* [ ] Musl libc support
* [ ] Check concurrency implementation
* [ ] Improved REPL UX
  * [ ] History and line edit (#11340)
  * [ ] Syntax highlighting (#11366)
* [ ] Windows support
  * [ ] Runtime loader for windows
* [ ] `asm` support (interpreter bytecode)
* [ ] More specs
* [ ] 96 other TODOs in `src/compiler/crystal/repl`

Feel free to post comments for additional items here.

**No discussion on individual items. Thank you** 🙇‍♂️ 

That should be moved to dedicated issues. If none exists, please open one or start an informal discussion at https://forum.crystal-lang.org/

**Comment by asterite** [comment]
I think pry doesn't work well in many cases. For example, block arguments are not visible. In general, I feel that pry has still a long way to go

**Comment by asterite** [comment]
After https://github.com/crystal-lang/crystal/pull/11578 is merged, the first thing I would do is to write at least one spec for `debugger` and `pry`. There's a lot to fix and improve there, and without tests it's going to be tough.

My idea was to have tests specify three things:
- a source, which has a `debugger` call in it
- given input
- expected output

For example:

```crystal
assert_interpreter_debugger(
  code: "a = 1; debugger; a",
  input: "a",
  expected_output: "1",
)
```

That is, after `debugger` is reached, the user types "a" on the console, and they expect to get "1" as the output.

This will require adapting the interpreter so that the input and output are not tied to STDIN and STDERR, which might also eventually make it possible to hook the interpreter into code editors.

These tests will also be independent of the underlying implementation, so they will be extremely useful and resilient to changes.

With those tests in place, I could start working on some of them to fix existing bugs, like https://github.com/crystal-lang/crystal/issues/11555#issuecomment-989295051

**Comment by beta-ziliani** [comment]
@asterite just to clarify, each of the lines stating [BUG: missing handling...](https://github.com/crystal-lang/crystal/blob/afaae3fb093bdfbf042c6ed7769b4190e06ff422/src/compiler/crystal/interpreter/primitives.cr#L178) is a TODO waiting to be completed, right? (Just stumble across one of this).

**Comment by asterite** [comment]
That's it! Maybe I should have put a TODO there 😅

**Comment by watzon** [comment]
I assume the issue that happens when attempting to `require "openssl"` or anything that relies on openssl is included in one of these subtasks? The issue seems to be different based on whether you require openssl in the repl or in a file the interpreter is running, but both break.

If other people aren't having this problem for some reason I'll gladly make a new issue.

**Comment by HertzDevil** [comment]
> That is, after `debugger` is reached, the user types "a" on the console, and they expect to get "1" as the output.

#12119 does this for LLDB. We could probably use FileCheck here or even use the same test source files for multiple debuggers (another one I have in my mind is GDB).

**Comment by mwgkgk** [comment]
https://github.com/Ivo-Balbaert/programming_crystal/blob/master/exercises/crystal_new/fibers.cr

Something really slow about channels. `crystal i <filename>` this thing grinds my computer to a halt i barely Ctrl-c'd at 1507 out of 10000 iterations. `crystal r <filename>` completes smoothly in a blink of an eye.

```
# START:p1
chan = Channel(String).new
i = 0
num = 10000
num.times do
  spawn do
    chan.send "fiber #{i}: I like crystals!"
  end
  i += 1
  puts chan.receive
end
# =>
# fiber 1: I like crystals!
# fiber 2: I like crystals!
# fiber 3: I like crystals!
# fiber 4: I like crystals!
# ...
# fiber 10000: I like crystals!
# END:p1
```

**Comment by mdwagner** [comment]
Can confirm similar results on MacOS (Intel) with Crystal 1.5.0

**Comment by asterite** [comment]
Yes, the interpreter is slower than compiled mode. And I have no immediate plans to improve its speed.
