### ISSUE TITLE
Support LLVM 15

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12743]
LLVM 15 has been released in September. We should update the LLVM bindings to support this version.

https://releases.llvm.org/15.0.0/docs/ReleaseNotes.html

Here are the list of subtasks that have to be done:

* [x] https://github.com/crystal-lang/crystal/pull/12623
* [x] Support typed LLVM `load` instructions (#12973)
* [x] Keep track of our own function types for typed LLVM `call` instructions (https://github.com/crystal-lang/crystal/issues/12743#issuecomment-1374240266, #13158)
* [x] Investigate why x86_64-darwin fails on certain LLVM versions (https://github.com/crystal-lang/crystal/pull/12623#issuecomment-1377368138)
* [x] Remove all pointer-to-pointer uses of the LLVM `bitcast` instruction (#13171)
* [x] Deprecate bindings / methods for the untyped variants in `LLVM::Builder` etc. (#13172)

**Comment by straight-shoota** [comment]
For LLVM 15 we need support for opaque pointers or opt-in to typed pointers (see #12484).

**Comment by Dan-Do** [comment]
Just tried compiling crystal latest branch on my Fedora rawhide. Error
`Makefile:192: *** "Could not locate compatible llvm-config, make sure it is installed and in your PATH, or set LLVM_CONFIG. Compatible versions: 14.0 13.0 12.0 11.1 11.0 10.0 9.0 8.0 7.1 6.0 5.0 4.0 3.9 3.8.  Stop.`
I had to manually add `LLVM_CONFIG=/usr/bin/llvm-config` to the command line.

**Comment by Dan-Do** [comment]
The compiler was built successfully, but terminate when compiling
```
Invalid memory access (signal 11) at address 0x0
[0x924006] *Exception::CallStack::print_backtrace:Nil +118 in ./.build/crystal
[0x8fa0b6] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +310 in ./.build/crystal
[0x7f0ccfa5e100] ?? +139693000089856 in /lib64/libc.so.6
[0x7f0cd0cfe9b6] LLVMGetElementType +22 in /lib64/libLLVM-15.so
[0x19bc49e] *LLVM::Function#function_type:LLVM::Type +30 in ./.build/crystal
[0x19c9103] *LLVM::ParameterCollection#size:Int32 +19 in ./.build/crystal
[0x19c909b] *LLVM::ParameterCollection +155 in ./.build/crystal
[0x19020b8] *Crystal::CodeGenVisitor#initialize<Crystal::Program, Crystal::ASTNode+, Bool, Crystal::Debug>:(LLVM::Value | Nil) +1064 in ./.build/crystal
[0x1901c86] *Crystal::CodeGenVisitor::new:single_module:debug<Crystal::Program, Crystal::ASTNode+, Bool, Crystal::Debug>:Crystal::CodeGenVisitor +198 in ./.build/crystal
[0xb36f12] *Crystal::Program#codegen<Crystal::ASTNode+, Bool, Crystal::Debug>:Hash(String, Crystal::CodeGenVisitor::ModuleInfo) +50 in ./.build/crystal
[0xb36edd] *Crystal::Program#codegen:debug:single_module<Crystal::ASTNode+, Crystal::Debug, Bool>:Hash(String, Crystal::CodeGenVisitor::ModuleInfo) +13 in ./.build/crystal
[0x17f4aea] *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) +426 in ./.build/crystal
[0x17f8d1b] *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +187 in ./.build/crystal
[0x1ab02b5] *Crystal::Command::CompilerConfig#compile<String>:Crystal::Compiler::Result +53 in ./.build/crystal
[0x1ab0261] *Crystal::Command::CompilerConfig#compile:Crystal::Compiler::Result +33 in ./.build/crystal
[0x1aa30e2] *Crystal::Command#build:Crystal::Compiler::Result +290 in ./.build/crystal
[0x1aa23fd] *Crystal::Command#run:(Bool | Nil) +397 in ./.build/crystal
[0x1aa2149] *Crystal::Command::run<Array(String)>:(Bool | Nil) +25 in ./.build/crystal
[0x1aa210d] *Crystal::Command::run:(Bool | Nil) +29 in ./.build/crystal
[0x8d760e] __crystal_main +2430 in ./.build/crystal
[0xaba006] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6 in ./.build/crystal
[0xab9f7a] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +58 in ./.build/crystal
[0x8e49b6] main +6 in ./.build/crystal
[0x7f0ccfa48a90] ?? +139693000002192 in /lib64/libc.so.6
[0x7f0ccfa48b49] __libc_start_main +137 in /lib64/libc.so.6
[0x8d6bc5] _start +37 in ./.build/crystal
[0x0] ???
```

**Comment by asterite** [comment]
Right, LLVM 15 won't work out of the box.

**Comment by anatol** [comment]
Any plans to add support for LLVM 15?

**Comment by beta-ziliani** [comment]
Not strictly related, but https://github.com/crystal-lang/crystal/pull/12623 is a step towards support for newer versions. But it's currently blocked because it's having issues with older (yet recent) versions of LLVM in Darwin.

**Comment by jemc** [comment]
I currently wrapping up migrating the [Savi compiler](https://github.com/savi-lang/savi) (which is written in Crystal, and uses Crystal's LLVM bindings) to LLVM 15, so I wanted to share some notes about it in case it helps Crystal make the migration to LLVM 15 more easily:

---

My first inclination was to opt out of opaque pointers using `LLVMContextSetOpaquePointers` to disable opaque pointers, so that I could deal with this later, before migrating to LLVM 16.

However, note that this is marked as "best effort" and "untested" in LLVM 15, and in practice when I tried this I saw various crashes in LLVM passes when I went to run the LLVM optimizer or the LLVM machine code emission processes. I had some programs compile and run successfully, but others crashed the compiler in the LLVM passes as described.

After a bit of trying to troubleshoot this, I made the assumption that the "best effort" in LLVM 15 to support legacy typed pointers just wasn't good enough to be bug-free, so I moved on to migrating my code to actually use opaque pointers.

---

The current implementation of `LLVM::Function#function_type` in Crystal relies on typed pointers, by using the `LLVMGlobalGetElementType` function to get the function type from the function pointer type:

```crystal
  def function_type
    Type.new LibLLVM.get_element_type(LibLLVM.type_of(self))
  end
```

If it's a "real" function (declared as a global name in the module), then the `LLVMGlobalGetValueType` can get the function type.

However, it should be noted that this only works for "real" defined global functions - not for function pointer values wrapped in an `LLVM::Function` wrapper via calling `LLVM::Function.from_value` - the latter will lead to a silently invalid type and there is no general way to get the function type out of such a pointer (given that it is an opaque pointer).

And this in turn means that `LLVM::Builder#call` needs to be modified to accept a separate parameter to specify the function type as an `LLVM::Type`, rather than silently using `func.function_type` to get the function type (because this won't work for function pointer values that aren't directly referencing a concrete global function. I had to deal with this for virtual dispatch, though I'm not sure if Crystal actually has virtual dispatch so this may be less relevant. I also dealt with it for inline asm-based functions.

---

Aside from `LLVM::Builder#call`, I also needed to replace the following methods to make them accept the pointer's pointee type as a new parameter:

- `LLVM::Builder#load`
- `LLVM::Builder#gep`
- `LLVM::Builder#inbounds_gep`
- `LLVM::Builder#struct_gep`

---

One helpful hint for an `alloca` value is that you can get the element type of it via `LLVMGetAllocatedType` - this can be a helpful workaround sometimes, similar to the `LLVMGlobalGetValueType` function for global value pointers.

**Comment by zw963** [comment]
I meet this issue when i rolling my arch linux to newest version.

```
Makefile:193: *** "Could not locate compatible llvm-config, make sure it is installed and in your PATH, or set LLVM_CONFIG. Compatible versions: 14.0 13.0 12.0 11.1 11.0 10.0 9.0 8.0 7.1 6.0 5.0 4.0 3.9 3.8.  Stop.
```

**Comment by Dan-Do** [comment]
The issue has gone, I think it can be closed.
```
./.build/crystal -v
Crystal 1.8.0-dev (2023-01-28)

LLVM: 15.0.7
Default target: x86_64-redhat-linux-gnu
```
