### ISSUE TITLE
Add support for PCRE2

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12790]
I've successfully ported the libpcre bindings to libpcre2 🚀.

This allows us to upgrade the regex engine from the seriously outdated old version of libpcre (see #11331)

It was pretty straightforward and the new library API is pretty similar, as expected. So I don't expect many issues when migrating the regex backend (except for some rare behaviour and syntax changes between pcre and pcre2).

Now it's about integrating the bindings into the codebase. It should be sufficient to select the regex engine backend at compile time. While technically possible to include bindings for both libraries and being able to load either at runtime would be possible, but I also introduce a lot of complexity for little benefit.
So my proposal is to extract the engine-specific bindings out of `Regex` and `MatchData`. They should be placed into the `Crystal` namespace and used as backend for the public API. At compile time we can detect which library version is available and chose to build bindings for that one (preferring `pcre2` if both would work?). A compile time flag should be able to override the automatic detection. 

While implementing the bindings I noticed the specs for `Regex` are very thin in some areas when the full spec suite passed despite a couple of stubs in the new bindings 😆 
So I've set out to fill out some missing specs and in the process, overhaul the entire thing in #12788 and #12789. It's very useful to have decent spec coverage in order to verify both backends are good in the end.

Finally we'll also need to setup CI so that we can run specs against both libpcre and libpcre2.

Roadmap:

* [x] Improve specs
  * [x] #12788
  * [x] #12789
* [x] Extract abstract API (#12802)
* [x] Implement bindings for libpcre2 <del>(#12840)</del><ins>(#12856)</ins>
* [x] Integrate specs with CI (#12856, #12847)
* [x] Enable JIT compiler #12866
* [x] Automatic selection of PCRE library version (#12978)
* [x] Provide PCRE2 in distribution packages (https://github.com/crystal-lang/distribution-scripts/pull/219)
* [x] Switch compiler to use PCRE2 (https://github.com/crystal-lang/crystal/pull/13084)

**Comment by asterite** [comment]
Great! But I don't understand: why not just use pcre 2 always?

**Comment by Blacksmoke16** [comment]
Can deff be part of a follow-up PR, but thoughts on how/if the [fast path API](https://www.pcre.org/current/doc/html/pcre2jit.html#SEC11) should be supported? Similar to PCRE1, there's a JIT mode available that we can use while having it fall back on normal mode if its not available. Tho then comes the question if we can just always use the fast path API given it's supported on all the platforms Crystal supports. Another option could be to use internally check if its supported and then opt the program into it somehow behind the scenes.

I'm currently using it in Athena's routing component and it provides a non-negligible performance boost, so definitely think it's worth discussing.

**Comment by straight-shoota** [comment]
> why not just use pcre 2 always?

I don't think we can immediately drop support for libpcre entirely because libpcre2 is not readily available everywhere. Dropping it would also be a huge disruption for our distribution packages. It's much easier to support both and gradually transition to PCRE2.

@Blacksmoke16 Those features should be fine to be added on top later. I don't think they're necessary right away. The primary goal is to have an MVP for `Regex` with libpcre2 to work as a replacement for libpcre. This enables a path forward for transitioning to PCRE2.

**Comment by Fryguy** [comment]
Love this.  This also enables other future transitions should someone want to try out, say, oniguruma.

**Comment by straight-shoota** [comment]
All boxes are ticked. Closing.
The current nightly builds are already shipping with PCRE2 support in both stdlib and compiler 🚀 

Let's hope for a smooth transition in Crystal projects 🤞 

Instructions on the migration process: https://crystal-lang.org/2023/03/02/crystal-is-upgrading-its-regex-engine/
