### ISSUE TITLE
Get rid of non-crystal topics in Github

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/crystal#4241]
Github [introduced topics](https://github.com/blog/2309-introducing-topics) a while ago. Most Crystal repos out there are on [crystal topic](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acrystal&type=Repositories), but there are (at the time of writing) [28 repos with crystal-language](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acrystal-language&type=Repositories) and [12 with crystallang](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acrystallang&type=Repositories).

For topics to be most useful, we should avoid fragmentation, so I'm raising issues in each of those repos to re-tag them. This issue here will be the umbrella issue to track this progress.

If you're a member of any of those repos' communities, please help us by only leaving the `crystal` topic in place.

- [x] opensas/json-mappings-generator#3
- [x] bew/mpv-crystal-simple-plugin#1
- [x] tempuser1909/Learning-Crystal-lang#1
- [x] cagataycali/kemal-heroku-example#1
- [x] dayvsonlima/steven-framework#1
- [x] bthachdev/crystal-design-patterns#1
- [x] petoem/haste-client#1
- [x] CodelessFuture/crystal-website#1
- [x] tmlee/crystal-pinyin#1
- [x] raysrashmi/kemal_chat_app#1
- [x] ctiapps/asterisk#2
- [x] Angarsk8/chat-app-demo#1
- [x] akwiatkowski/tremolite#1
- [x] akwiatkowski/ocranizer#1
- [x] decors/mastodon.cr#1
- [x] olbat/libgen#1
- [x] veelenga/crystal-zsh#4
- [x] samueleaton/sentry#11
- [x] guvencenanguvenal/mustafa#3
- [x] tbrand/route.cr#2
- [x] UteroOS/utero#43
- [x] tbrand/which_is_the_fastest#7
- [x] tbrand/zir#1
- [x] izniburak/turkish-number#1
- [x] tbpgr/atom_crystal_snippet_tb#2
- [x] bew/flag_parser.cr#1
- [x] l3kn/linalg#1
- [x] Givralix/pnm#1
- [x] Ivo-Balbaert/crystal_samples#1
- [x] topaz-crystal/topaz#7
- [x] Angarsk8/realtime-todo-app#1
- [x] miketheman/statsd.cr#7
- [x] osfx/open_exchange_rates#1
- [x] at-grandpa/clim#3
- [x] kirbyfan64/rcmake#1
- [x] TechMagister/i18n.cr#2
- [x] osfx/ocean_kit#1
- [x] TechMagister/kemalyst-generator#30
- [x] icyleaf/colorful.cr#1
- [x] jwoertink/godaddy-api.cr#1
- [x] maxpowa/noise#1
- [x] ujifgc/crmark#1
- [x] at-grandpa/clim-tools#1
- [x] idchlife/chrysalis-router#1
- [x] icyleaf/wasp#1
- [x] levups/http_dummy_crystal#1
- [x] paktek123/elasticsearch-crystal#1
- [x] levups/screencapload-crystal#1
- [x] creadone/brds#1
- [x] metaware/flipper#1
- [x] creadone/dl#1
- [x] instana/crystal-sensor#2
- [x] bararchy/crystal-fann#1
- [x] beanieboi/weltreise-log#1
- [x] werner/crystal_on_steroids#1
- [x] veelenga/any_setting#2
- [x] andrewhamon/cox#1
- [x] molovo/herd#1
- [x] molovo/tiny#1
- [x] karlbateman/sip-client#1
- [x] delef/geoip2.cr#4
- [x] WeebWare/Weebsite#1
- [ ] marksiemers/kemal-playground#1
- [ ] x89/primes#1
- [ ] ceph3us/mbedtls.cr#1
- [ ] Demonstrandum/Crystal-Maze#1
- [ ] nedpals/sharn#1
- [ ] Phitherek/auto-display-manager-cr#1
- [ ] benbarber/benbarber#1
- [ ] DougEverly/jsonfeed.cr#1

**Comment by matiasgarciaisaia** [comment]
For the record - [`crystallang` is dead](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acrystallang&type=Repositories), [`crystal-language` only has 9 repos left](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acrystal-language&type=Repositories).

**Comment by dayvsonlima** [comment]
[steven-framework](https://github.com/dayvsonlima/steven-framework) changed!

**Comment by molovo** [comment]
Removed from molovo/tiny and molovo/herd 👍

**Comment by asterite** [comment]
Maybe it's not worth keeping this issue open if issues are already open in the specific repos?

Please reopen otherwise.

**Comment by TheJF** [comment]
Removed from TheJF/antennas
