### ISSUE TITLE
Bootstrapping compiler on Windows (tracking bug)

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#9032]
I intend to do the minimal work needed to be able to compile the Crystal compiler to a Windows executable and then use that to compile the Crystal compiler.

Thanks to the work of others, we are close to this milestone, I'll just tie some loose ends.

I will reference the related pull requests here.

* [x] [Minimal Windows support for Process](https://github.com/crystal-lang/crystal/pull/9047)
    * [x] [Add Crystal::System::Process to split out system-specific implementations](https://github.com/crystal-lang/crystal/pull/9035)
        * [x] [Define PID type as Int64](https://github.com/crystal-lang/crystal/pull/9019)
    * [x] [Make Process::Status Windows-compatible](https://github.com/crystal-lang/crystal/pull/9021)
    * [x] [Rename Process kill methods to signal](https://github.com/crystal-lang/crystal/pull/9006)
* Improvements to Process support, not strictly necessary here:
  * [Implement transformation to a command line string](https://github.com/crystal-lang/crystal/pull/9043)
* [x] [Fix Windows codegen (LLVM globals) in non-singlemodule mode](https://github.com/crystal-lang/crystal/pull/8978)
* [x] [Allow building compiler without 'playground', to avoid dependency on sockets](https://github.com/crystal-lang/crystal/pull/9031)
* [x] [Fix compiler's reliance on shell expansion](https://github.com/crystal-lang/crystal/pull/9062)
* [x] [Miscellaneous Windows-related fixes in the compiler](https://github.com/crystal-lang/crystal/pull/9054)
* [x] [Make File.rename overwrite the destination file on Windows, like elsewhere](https://github.com/crystal-lang/crystal/pull/9038)
* [x] [Figure out how to pass LLVM-related args to the linker](https://github.com/crystal-lang/crystal/pull/9106)
* Semi-related to bootstrapping:
    * [Detection of the host system during cross-compilation](https://github.com/crystal-lang/crystal/pull/9049)

Note that this will **not** constitute full Windows support, it's just another step, but one that happens to make future porting work more convenient.

**Comment by asterite** [comment]
Let's do it!

Can we make the effort to not discuss small details until we can bootstrap in Windows? For example, I think it's fine to go with `alias PID = Int64` for now. Once we have it working on Windows we can revisit this (please leave a TODO somewhere). But right now I feel these discussions are less important than getting stuff done.

**Comment by oprypin** [comment]
I completely reworked [Porting to Windows](https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows) wiki. It fully explains how to bootstrap the compiler on Windows.

It assumes https://github.com/crystal-lang/crystal/pull/9106 is merged, as the very last requirement.

Thanks to everyone involved and especially @RX14.

**Comment by straight-shoota** [comment]
I checked the wiki entry, looks good! I'll try to follow the steps. Fortunately, I have a new workstation at hand where I haven't setup my Crystal windows environment yet 😆 
One thing I noticed is not explicitly mentioned but assumed later in the guide, is that you put cross-compiled object files into the windows working directory (`C:\windows`) and also to checkout the crystal repo there.

**Comment by oprypin** [comment]
There's no c:\\Windows involved!

**Comment by straight-shoota** [comment]
Sry, I meant `C:\crystal`

**Comment by straight-shoota** [comment]
Awesome! Thank you very much for taking up this task and finishing it in a record setting weeklong streek =) I didn't expect to move so much so fast. The ground had already been laid out by previous discussions and some PRs just needed the last finishing touch. But still, this is really a big step towards windows support.
